insert into public.categories (slug, name, parent_slug, blurb, sort) values
('police-arrest','Police & Arrest','lawyers','Police interactions, arrests, questioning and custody footage.',10),
('criminal-defense','Criminal Defense','lawyers','Criminal cases, defendants, investigations and defense preparation.',11),
('personal-injury','Personal Injury','lawyers','Car crashes, injuries, accident scenes and injury consultations.',12),
('workers-comp','Workers’ Compensation','lawyers','Workplace injuries, construction sites, employees and workers’ claims.',13),
('family-law','Family Law','lawyers','Divorce, custody, family disputes and related consultations.',14),
('immigration-law','Immigration Law','lawyers','Visas, immigration documents, border and citizenship-related footage.',15),
('bankruptcy','Bankruptcy & Finance','lawyers','Financial stress, debt, bankruptcy documents and financial consultations.',16),
('real-estate-law','Real Estate Law','lawyers','Property transactions, deeds, contracts and real estate disputes.',17),
('employment-law','Employment Law','lawyers','Workplace disputes, employees, HR meetings and employment documents.',18),
('insurance-claims','Insurance Claims','lawyers','Insurance adjusters, claims, paperwork and settlement discussions.',19),
('accident-scenes','Accident Scenes','lawyers','Vehicle collisions, road accidents, emergency response and damage.',20),
('evidence-investigation','Evidence & Investigation','lawyers','Evidence review, investigations, photographs, records and case preparation.',21),
('legal-research','Legal Research','lawyers','Attorneys researching cases, reading law books and working on computers.',22),
('negotiation','Negotiation & Settlement','lawyers','Settlement discussions, negotiations, mediation and attorney meetings.',23),
('mediation','Mediation','lawyers','Mediators, opposing parties, attorneys and dispute-resolution meetings.',24),
('depositions','Depositions & Testimony','lawyers','Depositions, witness questioning and testimony preparation.',25),
('jury-trial','Jury & Trial','lawyers','Jury selection, trial preparation, witnesses and courtroom proceedings.',26),
('client-intake','Client Intake','lawyers','New-client meetings, consultations, forms and case evaluations.',27),
('legal-tech','Legal Technology','lawyers','Lawyers using computers, case-management software and digital research.',28),
('legal-team','Legal Teamwork','lawyers','Attorneys collaborating, reviewing files and preparing cases.',29),
('law-firm-marketing','Law Firm Marketing','lawyers','Lawyers speaking to camera, office branding and professional promotional footage.',30),
('after-hours','After-Hours Legal Work','lawyers','Attorneys working late, reviewing cases and client communications.',31),
('legal-stress','Stress & Legal Pressure','lawyers','Worried clients, financial pressure, uncertainty and difficult legal situations.',32),
('courthouse','Court & Government Buildings','lawyers','Courthouses, government offices, entrances and exterior establishing shots.',33),
('legal-documents','Legal Documents','lawyers','Legal forms, signatures, paperwork, files and document review.',34),
('judges-court','Judges & Court Officials','lawyers','Judges, court proceedings, benches and courtroom activity.',35),
('law-enforcement','Law Enforcement','lawyers','Officers, patrol vehicles, investigations and police activity.',36),
('jail-prison','Corrections & Jail','lawyers','Detention facilities, visitation, custody and correctional environments.',37)
on conflict (slug) do update set name = excluded.name, parent_slug = excluded.parent_slug, blurb = excluded.blurb, sort = excluded.sort;
